---
- name: Implementing tags
  hosts: all
  tasks:
    - name: Install tree
      apt:
        name: tree
        state: present
        update_cache: yes
      tags: 
        - tree_installation
        - never
    - name: Create user
      user:
        name: Advik
        password: advik
      tags: 
        - user_creation
        - always
    - name: Copy passwd file
      copy:
        src: /etc/passwd
        dest: /tmp
...

