---
- name: Install git on all servers and clone a remote git repo
  hosts: all
  tasks:
    - name: Install git on all servers
      apt:
        name: git
        state: present
        update_cache: yes
    - name: clone remote github repo
      git:
        repo: https://github.com/Advik2000/advik.git
        dest: /tmp/newgit
...
